### PR TITLE
Added Python Logo

### LINKED ISSUE #11: I am making a <Python Programming Language> Logo
Hey @salil-naik 
I want to make a logo for Python Programming Language.

### PR DESCRIPTION
**Pull request by sujoy-coder**
## Description 
Python Logo is added

Fixes #11 

## image of the art below

Screenshot (164)

## Checklist:
To fill the checklists, put x inside the brackets. [x]

- [x] My code follows the guidelines of this project
- [x] I have tested my code and it works properly
- [x] I have added just one folder that includes my Art files (jsx and css)
- [ ] I have not edited App.js file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] This is my original code and I have NOT copied the code from anywhere else.

### CODE REVIEW

**Review by salil-naik — CHANGES_REQUESTED** [review]
HI @sujoy-coder. Please use CSS to make the art. Do not use SVG.

**Comment by sujoy-coder** [comment]
Hey @salil-naik I don't have the experience of designing with css. So can you please help me out with that .... :)

**Comment by salil-naik** [comment]
> Hey @salil-naik I don't have the experience of designing with css. So can you please help me out with that .... :)

Hi. Try to play around with HTML CSS. All you need to do is change the shape and size of the HTML elements with the help of CSS. You can try changing the border-radius, box-shadow, background-colors, and positioning.

**Comment by salil-naik** [comment]
Hi @sujoy-coder, I'm closing this PR for now. Open a fresh PR whenever you are ready.

**Pull request closed without merging**
