### PR TITLE
WhatsApp Logo

### LINKED ISSUE #29: I am making a Whatsapp logo
Please assign it to me

### PR DESCRIPTION
**Pull request by Charu271**
## Description 
WhatsApp Logo

Fixes #29

## Insert the image of the art below
image

## Checklist:
To fill the checklists, put x inside the brackets. [x]

- [X] My code follows the guidelines of this project
- [X] I have tested my code and it works properly
- [X] I have added just one folder that includes my Art files (jsx and css)
- [X] I have not edited App.js file
- [] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] This is my original code and I have NOT copied the code from anywhere else.

### CODE REVIEW

**Comment by salil-naik** [comment]
Hi @Charu271, you again made the PR to the main branch.

**Comment by salil-naik** [comment]
Change the base branch from `salil-naik:main` to `salil-naik:updates`

**Comment by Charu271** [comment]
@salil-naik  Okay. I thought you asked for changing the branch while commiting. Is it possible to change it in this PR only?

**Comment by salil-naik** [comment]
Yes, it is possible to change.

**Comment by Charu271** [comment]
@salil-naik  Is it fine now?

**Pull request merged**
