### PR TITLE
Made Reddit Logo

### LINKED ISSUE #138: I am making a Reddit Logo

### PR DESCRIPTION
**Pull request by GeekyGoyal**
## Description 
Made a Reddit Logo using CSS

Fixes #138 

## Insert the image of the art below
Screenshot (332)

## Checklist:
To fill the checklists, put x inside the brackets. [x]

- [x] My code follows the guidelines of this project
- [x] I have tested my code and it works properly
- [x] I have added just one folder that includes my Art files (jsx and css)
- [x] I have not edited App.js file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] This is my original code and I have NOT copied the code from anywhere else.

### CODE REVIEW

**Comment by salil-naik** [comment]
Hi @GeekyGoyal, please change the base branch to `salil-naik:updates`

**Comment by GeekyGoyal** [comment]
Done @salil-naik

**Review by salil-naik — APPROVED** [review]
Good job. 👏

**Comment by GeekyGoyal** [comment]
Thank You :)

**Pull request merged**
