### PR TITLE
Made a hat

### LINKED ISSUE #47: I am making a hat

### PR DESCRIPTION
**Pull request by apoorva567**
## Description 
tried making a hat

Fixes #47 

## Insert the image of the art below
hat

## Checklist:
To fill the checklists, put x inside the brackets. [x]

- [x] My code follows the guidelines of this project
- [x] I have tested my code and it works properly
- [x] I have added just one folder that includes my Art files (jsx and css)
- [x] I have not edited App.js file
- [] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] This is my original code and I have NOT copied the code from anywhere else.

### CODE REVIEW

**Comment by salil-naik** [comment]
Hi. Why were you not able to check the art? Need any help with it?

**Review by salil-naik — CHANGES_REQUESTED** [review]
Hi. You have not added the hat. Please add it.

**Comment by apoorva567** [comment]
I am new to github so i got confused. Do i have to make another PR?

**Comment by salil-naik** [comment]
Good job @apoorva567

**Pull request merged**
