### PR TITLE
Twitter logo added

### LINKED ISSUE #48: I am making a Twitter logo

### PR DESCRIPTION
**Pull request by aadityamp01**
## Description 
Please provide a 1 line description of your art
Twitter logo

Fixes #48 

## Insert the image of the art below
tlogo

## Checklist:
To fill the checklists, put x inside the brackets. [x]

- [x] My code follows the guidelines of this project
- [x] I have tested my code and it works properly
- [x] I have added just one folder that includes my Art files (jsx and css)
- [x] I have not edited App.js file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] This is my original code and I have NOT copied the code from anywhere else.

### CODE REVIEW

**Review by salil-naik — CHANGES_REQUESTED** [review]
Hi @aadityamp01, CSS art should be made using CSS. Remove SVG and try to make it using CSS.

**Comment by aadityamp01** [comment]
Hello @salil-naik, I have fixed the requested changes. Please review it! 🙂

**Comment by aadityamp01** [comment]
Please merge this PR @salil-naik

**Comment by salil-naik** [comment]
Hi @aadityamp01, I cannot merge this PR as the code is plagiarized.

**Comment by aadityamp01** [comment]
Hello @salil-naik can you please give me the reference how it is plagiarized, because I've used the regular code, please don't mind;

**Comment by salil-naik** [comment]
> Hello @salil-naik can you please give me the reference how it is plagiarized, because I've used the regular code, please don't mind;

https://codepen.io/rpdasilva/pen/pJsof @aadityamp01

**Pull request closed without merging**
